### ISSUE TITLE
Feedback S1->S2: Contributes to the personal development of more junior people

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#216] opened 2019-06-26 09:48 UTC
From S1 workshop:

- ~Inspired by the question "Can you be a terrible line manager and still tick the 'Contributes to the personal development of more junior people' competency?" The example given is just 'Line manages people'... so apparently yes you can.~ RM: this has been addressed in https://github.com/Financial-Times/engineering-progression/issues/216#issuecomment-517731065
- The wording of this competency is more relaxed than M->S1 (contributes here, but responsibility at M->S1)
- M->S1 equivalent has no examples
- Should the aspects of line management be split into several competencies, and then we find line managey and non-line managey examples of how they can be met

**Comment by alicebartlett** [comment] 2019-07-19 14:16
@wheresrhys not sure what the problem is with this competency / if you're proposing a solution. Can you reframe this issue to make it easier to pick up?

**Comment by wheresrhys** [comment] 2019-07-30 15:48
For reference, this is the problematic competency:

> Contributes to the personal development of more junior people, e.g.
> - Pairs with more junior team members
> - Mentors people
> - Line manages people
> - Writes blog posts
> - Gives talks at meet-ups or conferences

The problems raised are:

- If you're a line manager, but a terrible one, you have succeeded in providing an example here. Do we want this? (On reflection, we don't make a point of being pedantic about this elsewhere, so no need to do it here. This line already implictly means 'Line manages people well')
- The wording of this competency is more relaxed than M->S1, which uses "Has responsibility for others’ professional development, e.g."

The final point is that an alternative approach might be to dissect line management into its varying aspects and have separate competencies for each, for which line management could be an example of how to achieve it. E.g. one competency for each of the following

- Takes responsibility for the wellbeing of others
- Directs the career development of others
- ...

**Comment by rowanmanning** [comment] 2019-08-02 14:53
Based on a discussion between me, Mark, and Rhys, I don't think we need to say "does line management _well_". I think in all the competencies and examples the assumption is that you're doing a good job with them. You could perform _most_ of the examples badly, e.g. "Gives a tech talk", "Responds to questions on Slack about a particular technology or product" - these could be done badly but it's up to the line manager of the person being promoted to determine that.

Also, splitting into examples of what we think makes a good line manager is dangerously close to us taking on the task of defining what line management is at the FT. That's out of scope for the engineering competencies.

Sound OK?

**Comment by wheresrhys** [comment] 2019-08-02 20:12
There's the third point:
> The wording of this competency is more relaxed than M->S1, which uses "Has responsibility for others’ professional development, e.g.

...which is still totally valid

On splitting line management into separate competencies, I'm in favour, but agree it's tricky, and not something I'd stick my neck out on.

**Comment by rowanmanning** [comment] 2019-08-09 14:45
Closing this as we've resolved all issues except the second, which has been reopened as #251

**Closed by rowanmanning** 2019-08-09 14:45 UTC
Labels: area: leadership, level: M→S1, level: S1→S2
