### ISSUE TITLE
S1->S2 public speaking

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/engineering-progression#158] opened 2019-05-14 05:53 UTC
The question of "does everyone need to do public speaking? Doesn't that put introverts at a disadvantage?" came up.

There seemed to be a lack of clarity in the fact that examples are illustrative and that they don't all need to be met by candidates for promotion

This page helps https://github.com/Financial-Times/engineering-progression/issues/157 but it can be easily skipped

Do we need to make the `read how to use them here` link more prominent somehow in https://engineering-progression.ft.com/competencies/ ?

cc @umbobabo

**Comment by rowanmanning** [comment] 2019-05-17 08:41
Is this a possible duplicate of #149?

**Closed** 2019-05-18 05:33 UTC
Labels: level: S1→S2
