### ISSUE TITLE
M->S1->S2: What about teams that have few opportunities to get involved in hiring

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/engineering-progression#126] opened 2019-04-17 18:52 UTC
> Leads hiring process for new Engineers

For teams that aren't expanding, this competency can be unobtainable.

Does there need to be some leeway on this for some roughly equivalent staffing related activity? Or should the FT provide a more structured way for engineers - particularly S1 ones - to participate in the hiring process, regardless of their current team's level of recruitment

From discussions with @Limess and @ericanand

**Comment by rowanmanning** [comment] 2019-04-18 08:35
I think this is a duplicate of #97. We can reopen if you think there's a distinction

**Closed by rowanmanning** 2019-04-18 08:35 UTC
Labels: duplicate
